behaviors:
  FlappyBird:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005   #default: 0.005     권장 수치: 0.0001 ~ 0.01
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 1000000
    time_horizon: 128 
    summary_freq: 10000
environment_parameters:
  pipe_height:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: FlappyBird
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
        value: 30
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: FlappyBird
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.2
        value: 35
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: FlappyBird
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.3
        value: 40
      - name: Lesson3
        value: 45